### ISSUE TITLE
Importing Repo

### ISSUE THREAD

**Issue by Stoyvo** [mewkiz/flac#13]
Cannot install package due to directory name.

Example: 
```
go get -u github.com/mdlayher/waveform
package github.com/mdlayher/waveform
        imports github.com/azul3d/audio-flac
        imports gopkg.in/mewkiz/flac.v1/frame
        imports github.com/mewkiz/flac/internal/bits: use of internal package not allowed
package github.com/mdlayher/waveform
        imports github.com/azul3d/audio-flac
        imports gopkg.in/mewkiz/flac.v1/frame
        imports github.com/mewkiz/flac/internal/hashutil: use of internal package not allowed
package github.com/mdlayher/waveform
        imports github.com/azul3d/audio-flac
        imports gopkg.in/mewkiz/flac.v1/frame
        imports github.com/mewkiz/flac/internal/hashutil/crc16: use of internal package not allowed
package github.com/mdlayher/waveform
        imports github.com/azul3d/audio-flac
        imports gopkg.in/mewkiz/flac.v1/frame
        imports github.com/mewkiz/flac/internal/hashutil/crc8: use of internal package not allowed
```

**Comment by mewmew** [comment]
Hi @Stoyvo. Thanks for reporting this! My brother and I will take a look at it. Cheers /u

**Comment by mewmew** [comment]
Ah, I see the problem. With the move to a single repository for the Azul3D engine (see issue azul3d/engine#1), all of the old repositories have been moved to https://github.com/azul3d-legacy. As GitHub handles redirects the old import paths are still active, but the code is lagged behind. The fix would be to patch [waveform](https://github.com/mdlayher/waveform) to start making use of [azul3d.org/engine/audio](https://godoc.org/azul3d.org/engine/audio) and [azul3d.org/engine/audio/flac](https://godoc.org/azul3d.org/engine/audio/flac), rather than the old package import paths. Also, with this move, the Azul3D library introduced some cleanups to the audio API (see issue azul3d/engine#76).

A pull request has been submitted to the waveform package (see mdlayher/waveform#9), which will update its use of the audio package. I hope this should resolve the issue.

Cheers /u

**Comment by mewmew** [comment]
Hi @Stoyvo,

With mdlayher/waveform#9 now merged, this issue should have been resolved. Let us know if you bump into any other issues in the future. Closing this issue for now.

Cheers /u
